# Default values for cloud-firewall-controller.
replicaCount: 1

namespace: "kube-system"

image:
  repository: docker.io/hwagner/cloud-firewall-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "latest"

# Only needed if hosting a private copy of the image
# Update to match your private repository docker auth
imagePullSecrets: []
podAnnotations: {}
podLabels: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
