{{- if .Values.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: linode-cfw
  namespace: {{ required ".Values.namespace required" .Values.namespace }}
stringData:
  token: {{ required ".Values.apiToken required" .Values.apiToken }}
type: Opaque
{{- end }}
