---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-firewall-controller
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.linode.com
  resources:
  - cloudfirewalls
  - nodebalancerfirewalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.linode.com
  resources:
  - cloudfirewalls/finalizers
  - nodebalancerfirewalls/finalizers
  verbs:
  - update
- apiGroups:
  - networking.linode.com
  resources:
  - cloudfirewalls/status
  - nodebalancerfirewalls/status
  verbs:
  - get
  - patch
  - update 
